/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.PharmacyAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.Orders.Orders;
import Business.Pharmacy.Pharmacy;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik Poojari
 */
public class AdminManageOrders extends javax.swing.JPanel {

    
    JPanel userProcessContainer;
    Pharmacy pharmacy;
    public AdminManageOrders(JPanel userProcessContainer, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmacy = pharmacy;
        btnAssignDeliveryAgent.setEnabled(false);
        comboDeliveryAgent.setEnabled(false);
       
        lblValue.setText(pharmacy.getName());
        populateTable();
        comboDeliveryAgent.addItem("");
        System.out.println(pharmacy.getDeliveryManDirectory().getDeliveryManList().size());
        for(DeliveryMan dm : pharmacy.getDeliveryManDirectory().getDeliveryManList())
        {
            System.out.println(dm.getName());
            comboDeliveryAgent.addItem(dm.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssignDeliveryAgent = new javax.swing.JButton();
        lblCurrentOrders = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblValue = new javax.swing.JLabel();
        lblPharmacy = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        comboDeliveryAgent = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        btnAssignDeliveryAgent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssignDeliveryAgent.setText("Assign Delivery Agent");
        btnAssignDeliveryAgent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssignDeliveryAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDeliveryAgentActionPerformed(evt);
            }
        });
        add(btnAssignDeliveryAgent);
        btnAssignDeliveryAgent.setBounds(360, 490, 190, 50);

        lblCurrentOrders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCurrentOrders.setText("Current Orders");
        add(lblCurrentOrders);
        lblCurrentOrders.setBounds(450, 180, 140, 21);

        tblOrders.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No.", "Customer Name", "Order Date", "Delivery Man"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 250, 850, 210);

        lblValue.setBackground(new java.awt.Color(204, 204, 255));
        lblValue.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue);
        lblValue.setBounds(520, 40, 282, 30);

        lblPharmacy.setBackground(new java.awt.Color(204, 204, 255));
        lblPharmacy.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPharmacy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPharmacy.setText("Pharmacy");
        add(lblPharmacy);
        lblPharmacy.setBounds(220, 40, 292, 30);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete Button.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(790, 490, 150, 50);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back Button.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(830, 40, 110, 50);

        comboDeliveryAgent.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        add(comboDeliveryAgent);
        comboDeliveryAgent.setBounds(90, 490, 220, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/46c6cc94a14f2da88997d4df1d5efde7.jpg"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 1030, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignDeliveryAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryAgentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0)
        {
            Orders orders = (Orders) tblOrders.getValueAt(selectedRow, 0);
            if(comboDeliveryAgent.getSelectedItem() != "")
            {
                String dmName = comboDeliveryAgent.getSelectedItem().toString();
                DeliveryMan dm = pharmacy.findDeliveryMan(dmName);
                orders.setDeliveryMan(dm);
                JOptionPane.showMessageDialog(null, "Delivery man assigned successfully!");
                populateTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please select a delivery man!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAssignDeliveryAgentActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0)
        {
            comboDeliveryAgent.setEnabled(true);
            btnDelete.setEnabled(true);
            btnAssignDeliveryAgent.setEnabled(true);
        }
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0)
        {
            Orders orders = (Orders) tblOrders.getValueAt(selectedRow, 0);
            pharmacy.deleteOrder(orders);
            JOptionPane.showMessageDialog(null, "Order deleted successfully!");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignDeliveryAgent;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> comboDeliveryAgent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCurrentOrders;
    private javax.swing.JLabel lblPharmacy;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
    
    private void populateTable() {
       DefaultTableModel dtm = (DefaultTableModel)tblOrders.getModel();
        dtm.setRowCount(0);
        if(pharmacy.getOrderDirectory().getOrderList() != null)
        {
            for(Orders orders : pharmacy.getOrderDirectory().getOrderList())
            {
                if(!orders.isStatus())
                {
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = orders;
                    try {
                        row[1] = orders.getCustomer().getName();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    row[2] = orders.getOrderDate().format(formatter);
                    if(orders.getDeliveryMan() == null)
                    {
                        row[3] = "";
                    }
                    else
                    {
                        row[3] = orders.getDeliveryMan().getName();
                    }
                    dtm.addRow(row);
                }
            }
        }
        if(dtm.getRowCount() == 0)
            {
                comboDeliveryAgent.setEnabled(false);
                btnAssignDeliveryAgent.setEnabled(false);
            }
    }
}
