/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.PharmacyAdminRole;

import Business.EcoSystem;
import Pharmacy.Pharmacy;
import SupplierManager.SupplierManager;
import User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Pratik Poojari
 */
public class PharmacyAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyAreaJPanel
     */
    private JPanel userProcessContainer;
    private User user;
    Pharmacy pharmacy;
    EcoSystem system;
    SupplierManager supplierManager;
    public PharmacyAreaJPanel(JPanel userProcessContainer,User user, EcoSystem system, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  
        this.user = user;
        this.system = system;
        this.pharmacy=pharmacy;
        comboSupplier.addItem("");
        for(SupplierManager supplierManager : system.getSupplierManagerDirectory().getSupplierManagersList())
        {
            comboSupplier.addItem(supplierManager.getSupplierManagerName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValue = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPharmacyWorkArea = new javax.swing.JLabel();
        comboSupplier = new javax.swing.JComboBox<>();
        lblWelcome = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        btnReviewOrders = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblValue.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue);
        lblValue.setBounds(550, 120, 310, 40);

        lblSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setText("Choose a Supplier:");
        add(lblSupplier);
        lblSupplier.setBounds(110, 220, 210, 50);

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress);
        lblAddress.setBounds(220, 480, 90, 50);

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtName);
        txtName.setBounds(410, 400, 420, 50);

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtAddress);
        txtAddress.setBounds(410, 480, 420, 50);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(230, 410, 70, 40);

        lblPharmacyWorkArea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPharmacyWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPharmacyWorkArea.setText("Pharmacy Work Area");
        add(lblPharmacyWorkArea);
        lblPharmacyWorkArea.setBounds(220, 50, 580, 40);

        comboSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupplierActionPerformed(evt);
            }
        });
        add(comboSupplier);
        comboSupplier.setBounds(400, 220, 430, 50);

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWelcome.setText("Welcome! ");
        add(lblWelcome);
        lblWelcome.setBounds(370, 120, 150, 40);

        lblUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUpdate.setText("Update Details");
        add(lblUpdate);
        lblUpdate.setBounds(490, 330, 120, 50);

        btnReviewOrders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReviewOrders.setText("Review Orders");
        btnReviewOrders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOrdersActionPerformed(evt);
            }
        });
        add(btnReviewOrders);
        btnReviewOrders.setBounds(320, 570, 150, 50);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(620, 570, 150, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/46c6cc94a14f2da88997d4df1d5efde7.jpg"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 1030, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void comboSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupplierActionPerformed
        // TODO add your handling code here:
        if(comboSupplier.getSelectedItem() != "")
        {
            String supp = comboSupplier.getSelectedItem().toString();
            supplierManager = system.getSupplierManagerDirectory().findSupplierManager(supp);
            PharmacyOrderAction poa = new PharmacyOrderAction(userProcessContainer, pharmacy, supplierManager);
            userProcessContainer.add("CustomerOrder", poa);
            CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_comboSupplierActionPerformed

    private void btnReviewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOrdersActionPerformed
        // TODO add your handling code here:
       PharmacySummaryJPanel lcj = new PharmacySummaryJPanel(userProcessContainer, user, system, pharmacy);
       userProcessContainer.add("PharmacyOrder", lcj);
       CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewOrdersActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if((txtAddress.getText() == "")  )
        {
            JOptionPane.showMessageDialog(null,"Please fill all values!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            pharmacy.setPharmacyAddress(txtAddress.getText());

        }
        lblValue.setText(pharmacy.getPharmacyName());
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReviewOrders;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboSupplier;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPharmacyWorkArea;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
