/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SupplierAdminRole;

import Business.Supplier.Supplier;
import Business.SupplierDeliveryMan.SupplierDeliveryMan;
import Business.SupplierOrders.SupplierOrders;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik Poojari
 */
public class AdminManageSupplierOrders extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Supplier supplier;
    public AdminManageSupplierOrders(JPanel userProcessContainer, Supplier supplier) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = supplier;
        btnAssignDeliveryAgent.setEnabled(false);
        comboSupplierDeliveryAgent.setEnabled(false);

        lblValue.setText(supplier.getName());
        populateTable();
        comboSupplierDeliveryAgent.addItem("");
        System.out.println(supplier.getSupplierDeliveryManDirectory().getSupplierDeliveryManList().size());
        for (SupplierDeliveryMan sdm : supplier.getSupplierDeliveryManDirectory().getSupplierDeliveryManList()) {
            System.out.println(sdm.getName());
            comboSupplierDeliveryAgent.addItem(sdm.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblCurrentOrders = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        comboSupplierDeliveryAgent = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        btnAssignDeliveryAgent = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back Button.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 60, 120, 50);

        lblCurrentOrders.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCurrentOrders.setText("Current Orders");
        add(lblCurrentOrders);
        lblCurrentOrders.setBounds(430, 50, 170, 50);

        lblSupplier.setBackground(new java.awt.Color(255, 255, 255));
        lblSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSupplier.setText("Supplier");
        add(lblSupplier);
        lblSupplier.setBounds(390, 170, 90, 40);

        lblValue.setBackground(new java.awt.Color(255, 255, 255));
        lblValue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue);
        lblValue.setBounds(510, 170, 320, 40);

        comboSupplierDeliveryAgent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboSupplierDeliveryAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupplierDeliveryAgentActionPerformed(evt);
            }
        });
        add(comboSupplierDeliveryAgent);
        comboSupplierDeliveryAgent.setBounds(120, 460, 159, 40);

        tblOrders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No.", "Customer Name", "Order Date", "Delivery Man"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 240, 780, 190);

        btnAssignDeliveryAgent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAssignDeliveryAgent.setText("Assign Delivery Agent");
        btnAssignDeliveryAgent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssignDeliveryAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDeliveryAgentActionPerformed(evt);
            }
        });
        add(btnAssignDeliveryAgent);
        btnAssignDeliveryAgent.setBounds(330, 460, 190, 40);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete Button.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(780, 460, 120, 50);

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Medications02_Yellow@2x.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 1140, 860);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0) {
            comboSupplierDeliveryAgent.setEnabled(true);
            btnDelete.setEnabled(true);
            btnAssignDeliveryAgent.setEnabled(true);
        }


    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0) {
            SupplierOrders supplierOrders = (SupplierOrders) tblOrders.getValueAt(selectedRow, 0);
            supplier.deleteOrder(supplierOrders);
            JOptionPane.showMessageDialog(null, "Order deleted successfully!");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAssignDeliveryAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryAgentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow >= 0) {
            SupplierOrders supplierOrders = (SupplierOrders) tblOrders.getValueAt(selectedRow, 0);
            if (comboSupplierDeliveryAgent.getSelectedItem() != "") {
                String dmName = comboSupplierDeliveryAgent.getSelectedItem().toString();
                SupplierDeliveryMan sdm = supplier.findSupplierDeliveryMan(dmName);
                supplierOrders.setSupplierDeliveryMan(sdm);
                JOptionPane.showMessageDialog(null, "Delivery man assigned successfully!");
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Please select a delivery man!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAssignDeliveryAgentActionPerformed

    private void comboSupplierDeliveryAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupplierDeliveryAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSupplierDeliveryAgentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignDeliveryAgent;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> comboSupplierDeliveryAgent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCurrentOrders;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblOrders.getModel();
        dtm.setRowCount(0);
        if (supplier.getSupplierOrderDirectory().getSupplierOrderList() != null) {
            for (SupplierOrders supplierOrders : supplier.getSupplierOrderDirectory().getSupplierOrderList()) {
                if (!supplierOrders.isStatus() && supplierOrders.getPharmacy() != null) {
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = supplierOrders;
                    row[1] = supplierOrders.getPharmacy().getName();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    row[2] = supplierOrders.getOrderDate().format(formatter);
                    if (supplierOrders.getSupplierDeliveryMan() == null) {
                        row[3] = "";
                    } else {
                        row[3] = supplierOrders.getSupplierDeliveryMan().getName();
                    }
                    dtm.addRow(row);
                }
            }
        }
        if (dtm.getRowCount() == 0) {
            comboSupplierDeliveryAgent.setEnabled(false);
            btnAssignDeliveryAgent.setEnabled(false);
        }
    }
}
