/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DrugMinistry;

import Business.EcoSystem;
import Business.Drugs.Drugs;
import Business.Drugs.DrugsDirectory;
import java.awt.CardLayout;
//import Business.Supplier.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chengyen lai
 */
public class DrugApprovalJPanel extends javax.swing.JPanel {

 
    private JPanel UserProccessContainerSAMC;
    private EcoSystem ecosystem;
   
    public DrugApprovalJPanel(JPanel userProccessContainer, EcoSystem ecosystem) {
        initComponents();
        this.UserProccessContainerSAMC = userProccessContainer;
        this.ecosystem = ecosystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_drug = new javax.swing.JTextField();
        txt_Components = new javax.swing.JTextField();
        btn_Publish = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DrugApproval = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        text_disease = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 759));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Health Ministry");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Drug :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Components :");

        txt_drug.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_drug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drugActionPerformed(evt);
            }
        });

        txt_Components.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Components.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ComponentsActionPerformed(evt);
            }
        });

        btn_Publish.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Publish.setText("List");
        btn_Publish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PublishActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete Button.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbl_DrugApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tbl_DrugApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DRUG", "Components", "Disease"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_DrugApproval);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID :");

        txt_Id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });

        text_disease.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Disease :");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back Button.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btn_view.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/View Button.png"))); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Components, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_disease)
                            .addComponent(txt_drug)
                            .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_view, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(btn_Publish, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_disease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(btn_view)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_drug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Components, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btn_Publish, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_drugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drugActionPerformed

    private void txt_ComponentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ComponentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ComponentsActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_DrugApproval.getSelectedRow();
        if (selectedRow >= 0)
        {
            Drugs selectedDrugs = (Drugs) tbl_DrugApproval.getValueAt(selectedRow, 1);
            ecosystem.getDrugsDirectory().deleteDrugs(selectedDrugs);
            JOptionPane.showMessageDialog(null, "Drugs " + selectedDrugs.getDrugName()+ " deleted successfully!");
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_PublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PublishActionPerformed
        // TODO add your handling code here:
        Drugs pe = ecosystem.getDrugsDirectory().createDrugs(txt_Id.getText(),txt_drug.getText(),txt_Components.getText(), text_disease.getText());
        System.out.println(pe);
      //  supplier se = new supplier(pe);
        if(pe == null)
        {
            JOptionPane.showMessageDialog(null,"Drugs " + txt_drug.getText() + " already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Drugs successfully Published ");
            
        }
         txt_Id.setText("");
         txt_drug.setText("");
         text_disease.setText("");
         txt_Components.setText("");
         
        populateTable();
    }//GEN-LAST:event_btn_PublishActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
//         int selectedRowIndex = tbl_DrugApproval.getSelectedRow();
//                
//           if (selectedRowIndex<0) {
//               
//               JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//               return;
//           }
//           
//           DefaultTableModel model = (DefaultTableModel) tbl_DrugApproval.getModel();
//            selectedEmployee_Details  = (Drugs) model.getValueAt(selectedRowIndex, 1);
//           
//           txtName.setText(String.valueOf(selectedEmployee_Details.getName()));
        
        
        
        
         DefaultTableModel model= (DefaultTableModel) tbl_DrugApproval.getModel();
        if(tbl_DrugApproval.getSelectedRowCount()==1){
            
        int selectedRowIndex = tbl_DrugApproval.getSelectedRow();
           //DefaultTableModel model1 = (DefaultTableModel) tbl_SA_PatientDirectory.getModel();
        Drugs selectedDrugs_Details  = (Drugs) model.getValueAt(selectedRowIndex, 1);
         //  int row = DrugsDirectory.getDru().indexOf(selectedPatientD_Details);
        
//         txt_drug.setText(String.valueOf(selectedDrugs_Details.getDrugName()));
//         txt_Components.setText(String.valueOf(selectedDrugs_Details.getDrugCompostion()));
//         text_disease.setText(String.valueOf(selectedDrugs_Details.getDisease()));
//         txt_Id.setText(String.valueOf(selectedDrugs_Details.getId()));   
                 
         selectedDrugs_Details.setDrugName(txt_drug.getText());
         selectedDrugs_Details.setDrugCompostion(txt_Components.getText());
         selectedDrugs_Details.setDisease(text_disease.getText());
         selectedDrugs_Details.setId(txt_Id.getText());
        }
        
        populateTable();
        txt_Id.setText("");
        txt_drug.setText("");
        text_disease.setText("");
        txt_Components.setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserProccessContainerSAMC.remove(this);
        CardLayout layout = (CardLayout) UserProccessContainerSAMC.getLayout();
        layout.previous(UserProccessContainerSAMC);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tbl_DrugApproval.getSelectedRow();
                
           if (selectedRowIndex<0) {
               
               JOptionPane.showMessageDialog(this, "Please select a row to delete.");
               return;
           }
           
        DefaultTableModel model = (DefaultTableModel) tbl_DrugApproval.getModel();
        Drugs selectedDrugs_Details  = (Drugs) model.getValueAt(selectedRowIndex, 1);
           
         txt_drug.setText(String.valueOf(selectedDrugs_Details.getDrugName()));
         txt_Components.setText(String.valueOf(selectedDrugs_Details.getDrugCompostion()));
         text_disease.setText(String.valueOf(selectedDrugs_Details.getDisease()));
         txt_Id.setText(String.valueOf(selectedDrugs_Details.getId())); 
         
    }//GEN-LAST:event_btn_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_Publish;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DrugApproval;
    private javax.swing.JTextField text_disease;
    private javax.swing.JTextField txt_Components;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_drug;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tbl_DrugApproval.getModel();
        dtm.setRowCount(0); //deletes the empty records  
        int count1 = 1;
        if(ecosystem.getDrugsDirectory().getDrugsList()!= null)
        {
            for(Drugs s : ecosystem.getDrugsDirectory().getDrugsList())
            {
                Object[] row = new Object[dtm.getColumnCount()]; //creates an array
                row[0] = s.getId();
                row[1] = s;
                row[2] = s.getDrugCompostion();
                row[3] = s.getDisease();
                dtm.addRow(row);
                count1++;
            }
        }
        else
        {
            tbl_DrugApproval.setEnabled(false);
        }
    }




}
