/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.DrugMinistry.DrugApprovalJPanel;


/**
 *
 * @author Pratik Poojari
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

     JPanel userProcessContainerSAWAP;
    EcoSystem ecosystemSAWAP;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainerSAWAP = userProcessContainer;
        this.ecosystemSAWAP = ecosystem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnManageCustomersSAWAP = new javax.swing.JButton();
        btnManagePharmacySAWAP = new javax.swing.JButton();
        BtnManageHospital = new javax.swing.JButton();
        BtnManageSupplier = new javax.swing.JButton();
        btn_DrugApproval = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tiro Bangla", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Administrator Panel");
        jPanel2.add(lblTitle);
        lblTitle.setBounds(370, 50, 490, 60);

        btnManageCustomersSAWAP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageCustomersSAWAP.setText("Manage Customers");
        btnManageCustomersSAWAP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCustomersSAWAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersSAWAPActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageCustomersSAWAP);
        btnManageCustomersSAWAP.setBounds(40, 200, 190, 60);

        btnManagePharmacySAWAP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManagePharmacySAWAP.setText("Manage Pharmacy");
        btnManagePharmacySAWAP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManagePharmacySAWAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePharmacySAWAPActionPerformed(evt);
            }
        });
        jPanel2.add(btnManagePharmacySAWAP);
        btnManagePharmacySAWAP.setBounds(780, 200, 190, 60);

        BtnManageHospital.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnManageHospital.setText("Manage Hospital");
        BtnManageHospital.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnManageHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageHospitalActionPerformed(evt);
            }
        });
        jPanel2.add(BtnManageHospital);
        BtnManageHospital.setBounds(440, 360, 190, 70);

        BtnManageSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnManageSupplier.setText("Manage Supplier");
        BtnManageSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnManageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageSupplierActionPerformed(evt);
            }
        });
        jPanel2.add(BtnManageSupplier);
        BtnManageSupplier.setBounds(50, 550, 210, 70);

        btn_DrugApproval.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_DrugApproval.setText("Drug Approval ");
        btn_DrugApproval.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_DrugApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DrugApprovalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_DrugApproval);
        btn_DrugApproval.setBounds(760, 560, 200, 70);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/HD-wallpaper-what-caregivers-need-to-know-about-schizophrenia-treatment-cute-pharmacy.v1 (1).jpg"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(1024, 759));
        lblBackground.setMinimumSize(new java.awt.Dimension(1024, 759));
        jPanel2.add(lblBackground);
        lblBackground.setBounds(0, -120, 1210, 1080);

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomersSAWAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersSAWAPActionPerformed
        SystemAdminManageCustomers uc = new SystemAdminManageCustomers(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserCustomer", uc);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
    }//GEN-LAST:event_btnManageCustomersSAWAPActionPerformed

    private void btnManagePharmacySAWAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePharmacySAWAPActionPerformed
        SystemAdminManagePharmacy um = new SystemAdminManagePharmacy(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserManager", um);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
    }//GEN-LAST:event_btnManagePharmacySAWAPActionPerformed

    private void BtnManageHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageHospitalActionPerformed
        // TODO add your handling code here:
        SystemAdminManageHospitals uc = new SystemAdminManageHospitals(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserHospital", uc);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
        
    }//GEN-LAST:event_BtnManageHospitalActionPerformed

    private void BtnManageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageSupplierActionPerformed
        // TODO add your handling code here:
        SystemAdminManageSupplier ms = new SystemAdminManageSupplier(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserSupplier", ms);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
        

    }//GEN-LAST:event_BtnManageSupplierActionPerformed

    private void btn_DrugApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DrugApprovalActionPerformed
        // TODO add your handling code here:

        DrugApprovalJPanel da = new DrugApprovalJPanel(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserSupplier", da);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);

    }//GEN-LAST:event_btn_DrugApprovalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageHospital;
    private javax.swing.JButton BtnManageSupplier;
    private javax.swing.JButton btnManageCustomersSAWAP;
    private javax.swing.JButton btnManagePharmacySAWAP;
    private javax.swing.JButton btn_DrugApproval;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
