/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package userinterface.HospitalRole;

import Business.Customer.Customer;
import Business.Hospital.Hospital;
import Business.MedicineItems.MedicineItem;
import Business.Orders.Orders;
import Business.Pharmacy.Pharmacy;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author cylai
 */
public class HospitalOrderAction extends javax.swing.JPanel{
    
    JPanel userProcessContainer;
    Customer customer;
    Pharmacy pharma;
    Orders orders;
    int totalAmount = 0;
    Hospital hospital;
    ArrayList<MedicineItem> cart = new ArrayList<MedicineItem>();


    public HospitalOrderAction(JPanel userProcessContainer, Hospital hospital, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
        this.pharma = pharmacy;
       
        populateMedicine1(); 
        populateOrder1();
        if(HOAOrderTable.getRowCount() <= 0)
        {
            HOAOrderButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")



    private void HOAOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        orders = pharma.getOrderDirectory().createNewOrderH(hospital);
        for(MedicineItem mo : cart)
        {
            orders.addItem(mo);
        }
        orders.calculateTotalAmount();
        JOptionPane.showMessageDialog(null, "Thank you for your order! Order of " + orders.getMedicineItemList().size() + " medicine item(s) for amount $" + orders.getTotalAmount() + " is placed successfully!");
    }















}
