/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.PharmacyAdminRole;

import Business.EcoSystem;
import Business.Pharmacy.Pharmacy;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pratik Poojari
 */
public class PharmacyAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Pharmacy pharmacy;
    EcoSystem system;
    Supplier supplier;

    public PharmacyAreaJPanel(JPanel userProcessContainer, UserAccount user, EcoSystem system, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = user;
        this.system = system;
        this.pharmacy = pharmacy;
        comboSupplier.addItem("");
        for (Supplier s : system.getSupplierDirectory().getSupplierList()) {
            comboSupplier.addItem(s.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplier = new javax.swing.JLabel();
        lblPharmacyWorkArea = new javax.swing.JLabel();
        comboSupplier = new javax.swing.JComboBox<>();
        lblWelcome = new javax.swing.JLabel();
        btnReviewOrders = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(null);

        lblSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setText("Choose a Supplier:");
        add(lblSupplier);
        lblSupplier.setBounds(110, 220, 210, 50);

        lblPharmacyWorkArea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPharmacyWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPharmacyWorkArea.setText("Pharmacy Work Area");
        add(lblPharmacyWorkArea);
        lblPharmacyWorkArea.setBounds(220, 50, 580, 40);

        comboSupplier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupplierActionPerformed(evt);
            }
        });
        add(comboSupplier);
        comboSupplier.setBounds(400, 220, 430, 50);

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWelcome.setText("Welcome! ");
        add(lblWelcome);
        lblWelcome.setBounds(370, 120, 150, 40);

        btnReviewOrders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReviewOrders.setText("Review Orders");
        btnReviewOrders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOrdersActionPerformed(evt);
            }
        });
        add(btnReviewOrders);
        btnReviewOrders.setBounds(460, 390, 220, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Medomand-online-Pharmacy-supply-1024x759.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(20, 0, 1030, 810);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back Button.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 30, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void comboSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupplierActionPerformed
        // TODO add your handling code here:
        if (comboSupplier.getSelectedItem() != "") {
            String supp = comboSupplier.getSelectedItem().toString();
            supplier = system.getSupplierDirectory().findSupplier(supp);
            PharmacyOrderAction poa = new PharmacyOrderAction(userProcessContainer, pharmacy, supplier);
            userProcessContainer.add("CustomerOrder", poa);
            CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_comboSupplierActionPerformed

    private void btnReviewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOrdersActionPerformed
        // TODO add your handling code here:
        PharmacySummaryJPanel lcj = new PharmacySummaryJPanel(userProcessContainer, userAccount, system, pharmacy);
        userProcessContainer.add("PharmacyOrder", lcj);
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewOrdersActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReviewOrders;
    private javax.swing.JComboBox<String> comboSupplier;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPharmacyWorkArea;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
